# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

#services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

# app/config/services.yml
services:
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    app.profile.form.type:
        class: AppBundle\Form\ProfileType
        tags:
            - { name: form.type, alias: app_user_profile }
    app.registration_listener:
        class: AppBundle\EventListener\RegistrationListener
        arguments:
            - @security.context
        tags:
            - { name: kernel.event_subscriber }
