# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

#services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

# app/config/services.yml
services:
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    app.profile.form.type:
        class: AppBundle\Form\ProfileType
        tags:
            - { name: form.type, alias: app_user_profile }
    app.locale_listener:
        class: AppBundle\EventListener\LocaleListener
        arguments:
            - @security.token_storage
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 11 }
            - { name: kernel.event_listener, event: security.interactive_login }
    app.registration_listener:
        class: AppBundle\EventListener\RegistrationListener
        arguments:
            - @security.context
            - @fos_user.util.token_generator
            - @router
        tags:
            - { name: kernel.event_subscriber }
    fos_user.listener.authentication:
        class: AppBundle\EventListener\AuthenticationListener
        arguments:
            - @fos_user.security.login_manager
            - 'main'
        tags:
            - { name: kernel.event_subscriber }
    app.document_uploader.directory_namer:
        class: AppBundle\Service\DirectoryNamer
        arguments: [%kernel.root_dir%]
    app.document_uploader.file_namer:
        class: AppBundle\Service\FileNamer
        arguments: [%kernel.root_dir%]
    app.twig_extension:
        class: AppBundle\Twig\LocaleExtension
        public: false
        tags:
            - { name: twig.extension }
    